name: Build and push Docker image to DockerHub
on: push
jobs:
  push_to_repository:
    name: Push Docker image to DockerHub
    runs-on: ubuntu-latest
    steps:
# Checks out the entire code and gives to the Github actions
      - name: checkout my rep code
        uses: actions/checkout@v3
# from Github actions market place to login, build and push image to dockerhub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push image to dockerhub
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: akilesh1997/docker-git-integrated:githubaction_docker